import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <nav className="bg-gray-800 p-4">
              <div className="max-w-6xl mx-auto flex justify-between items-center">
                  <div className="text-white text-lg font-semibold">Uzay Toprak</div>
                  <div className="space-x-4">
                      <Link href={"/"} className="text-gray-300 hover:text-white">Home</Link>
                      <Link href={"/blog"} className="text-gray-300 hover:text-white">Blog</Link>
                      <Link href={"/contact"} className="text-gray-300 hover:text-white">Contact</Link>
                  </div>
              </div>
          </nav>
        {children}
      </body>
    </html>
  )
}
